import { TaskType } from '@prisma/client'

export interface ScheduleTemplate {
  taskType: TaskType
  title: string
  description?: string
  time: string
  points: number
  icon: string
  isFixed: boolean
}

export const WEEKDAY_SCHEDULE: ScheduleTemplate[] = [
  {
    taskType: 'WAKE_UP',
    title: '起床',
    description: '新的一天开始了！',
    time: '07:30',
    points: 5,
    icon: 'sun',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '洗漱',
    description: '刷牙洗脸，精神满满',
    time: '07:40',
    points: 5,
    icon: 'sparkles',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '早餐',
    description: '营养早餐，开启美好一天',
    time: '08:00',
    points: 10,
    icon: 'utensils',
    isFixed: true,
  },
  {
    taskType: 'SCHOOL',
    title: '上学',
    description: '快乐学习时光',
    time: '08:30',
    points: 0,
    icon: 'book-open',
    isFixed: true,
  },
  {
    taskType: 'SCHOOL',
    title: '放学',
    description: '放学回家啦',
    time: '15:50',
    points: 0,
    icon: 'home',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '水果/休息',
    description: '补充能量，放松一下',
    time: '16:20',
    points: 5,
    icon: 'apple',
    isFixed: true,
  },
  {
    taskType: 'HOMEWORK',
    title: '学校作业',
    description: '完成今天的学校作业',
    time: '16:40',
    points: 15,
    icon: 'pencil',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '晚餐',
    description: '和家人一起吃晚餐',
    time: '18:00',
    points: 10,
    icon: 'utensils-crossed',
    isFixed: true,
  },
  {
    taskType: 'ENGLISH',
    title: '英语打卡',
    description: '每日英语练习',
    time: '18:40',
    points: 10,
    icon: 'languages',
    isFixed: true,
  },
  {
    taskType: 'MATH',
    title: '数学练习',
    description: '完成2面数学练习',
    time: '19:00',
    points: 20,
    icon: 'calculator',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '自由活动',
    description: '做自己喜欢的事情',
    time: '20:00',
    points: 5,
    icon: 'gamepad-2',
    isFixed: true,
  },
  {
    taskType: 'READING',
    title: '睡前阅读',
    description: '阅读30分钟',
    time: '21:20',
    points: 15,
    icon: 'book',
    isFixed: true,
  },
  {
    taskType: 'SLEEP',
    title: '睡觉',
    description: '晚安，做个好梦',
    time: '22:00',
    points: 10,
    icon: 'moon',
    isFixed: true,
  },
]

export const FRIDAY_SCHEDULE: ScheduleTemplate[] = [
  ...WEEKDAY_SCHEDULE.filter(item => item.time !== '15:50'),
  {
    taskType: 'SCHOOL',
    title: '放学',
    description: '周五放学啦！',
    time: '17:00',
    points: 0,
    icon: 'home',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '水果/休息',
    description: '补充能量，放松一下',
    time: '17:30',
    points: 5,
    icon: 'apple',
    isFixed: true,
  },
  {
    taskType: 'HOMEWORK',
    title: '学校作业',
    description: '完成今天的学校作业',
    time: '18:00',
    points: 15,
    icon: 'pencil',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '晚餐',
    description: '和家人一起吃晚餐',
    time: '19:30',
    points: 10,
    icon: 'utensils-crossed',
    isFixed: true,
  },
  {
    taskType: 'ENGLISH',
    title: '英语打卡',
    description: '每日英语练习',
    time: '20:10',
    points: 10,
    icon: 'languages',
    isFixed: true,
  },
  {
    taskType: 'MATH',
    title: '数学练习',
    description: '完成2面数学练习',
    time: '20:30',
    points: 20,
    icon: 'calculator',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '自由活动',
    description: '做自己喜欢的事情',
    time: '21:30',
    points: 5,
    icon: 'gamepad-2',
    isFixed: true,
  },
  {
    taskType: 'READING',
    title: '睡前阅读',
    description: '阅读30分钟',
    time: '22:00',
    points: 15,
    icon: 'book',
    isFixed: true,
  },
  {
    taskType: 'SLEEP',
    title: '睡觉',
    description: '晚安，做个好梦',
    time: '22:40',
    points: 10,
    icon: 'moon',
    isFixed: true,
  },
]

export const WEEKEND_SCHEDULE: ScheduleTemplate[] = [
  {
    taskType: 'WAKE_UP',
    title: '起床',
    description: '周末愉快！',
    time: '08:00',
    points: 5,
    icon: 'sun',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '洗漱',
    description: '刷牙洗脸，精神满满',
    time: '08:10',
    points: 5,
    icon: 'sparkles',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '早餐',
    description: '营养早餐，开启美好一天',
    time: '08:30',
    points: 10,
    icon: 'utensils',
    isFixed: true,
  },
  {
    taskType: 'HOMEWORK',
    title: '周末作业',
    description: '完成周末作业',
    time: '09:00',
    points: 20,
    icon: 'pencil',
    isFixed: true,
  },
  {
    taskType: 'ENGLISH',
    title: '英语打卡',
    description: '每日英语练习',
    time: '10:30',
    points: 10,
    icon: 'languages',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '户外活动',
    description: '出去运动或玩耍',
    time: '11:30',
    points: 15,
    icon: 'bike',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '午餐',
    description: '和家人一起吃午餐',
    time: '12:30',
    points: 10,
    icon: 'utensils-crossed',
    isFixed: true,
  },
  {
    taskType: 'READING',
    title: '午间阅读',
    description: '阅读30分钟',
    time: '14:00',
    points: 15,
    icon: 'book',
    isFixed: true,
  },
  {
    taskType: 'MATH',
    title: '数学练习',
    description: '完成2面数学练习',
    time: '15:00',
    points: 20,
    icon: 'calculator',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '自由时间',
    description: '做自己喜欢的事情',
    time: '16:00',
    points: 5,
    icon: 'gamepad-2',
    isFixed: true,
  },
  {
    taskType: 'BREAKFAST',
    title: '晚餐',
    description: '和家人一起吃晚餐',
    time: '18:00',
    points: 10,
    icon: 'utensils-crossed',
    isFixed: true,
  },
  {
    taskType: 'FREE_TIME',
    title: '家庭时光',
    description: '和家人一起做些有趣的事',
    time: '19:00',
    points: 10,
    icon: 'heart',
    isFixed: true,
  },
  {
    taskType: 'READING',
    title: '睡前阅读',
    description: '阅读30分钟',
    time: '21:00',
    points: 15,
    icon: 'book',
    isFixed: true,
  },
  {
    taskType: 'SLEEP',
    title: '睡觉',
    description: '晚安，做个好梦',
    time: '21:30',
    points: 10,
    icon: 'moon',
    isFixed: true,
  },
]

export function getScheduleForDate(date: Date): ScheduleTemplate[] {
  const day = date.getDay()
  if (day === 0 || day === 6) {
    return WEEKEND_SCHEDULE
  } else if (day === 5) {
    return FRIDAY_SCHEDULE
  } else {
    return WEEKDAY_SCHEDULE
  }
}
